/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 camera.gltf --transform
Author: santy (https://sketchfab.com/Santy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/camera-canon-eos-400d-c8c3f307e93f4c829d579d1b369e6b02
Title: Camera CANON EOS 400D
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/camera-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, -0.01]} scale={0.93}>
        <mesh
          geometry={nodes.cilindro_low1_Cilindro_material_0.geometry}
          material={materials.Cilindro_material}
        />
        <mesh
          geometry={nodes.cilindro_low1_lambert3_0.geometry}
          material={materials.lambert3}
        />
        <mesh
          geometry={nodes.cilindro_low1_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          geometry={nodes.cilindro_low1_lambert4_0.geometry}
          material={materials.lambert4}
        />
      </group>
      <mesh
        geometry={nodes.Mid_2_Camara_material_0.geometry}
        material={materials.Camara_material}
        position={[0, 0, -0.69]}
        scale={[2.02, 1.97, 1.26]}
      />
      <mesh
        geometry={nodes.pCylinder9_ruleta__0.geometry}
        material={materials.ruleta}
        position={[-1.13, 1.08, -0.8]}
        rotation={[0, 0.02, 0.24]}
        scale={[0.31, 0.05, 0.31]}
      />
      <mesh
        geometry={nodes.pCylinder8_ruleta_2_0.geometry}
        material={materials.ruleta_2}
        position={[-1.63, 0.79, 0.09]}
        rotation={[1.56, 0.01, -0.04]}
        scale={[0.18, 0.03, 0.18]}
      />
    </group>
  );
}

useGLTF.preload("/camera-transformed.glb");
