/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 css_logo_3d_model.gltf --transform
Author: Erik Egnatosyan (https://sketchfab.com/sans.egnatosyan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/css-logo-3d-model-17b34c2b98714c6799544939f476eed3
Title: CSS logo 3d model
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/css_logo_3d_model-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -1.58]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[20.79, 136.75, 10.17]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group position={[326.27, 35.49, 1926.62]}>
              <mesh
                geometry={nodes.Object_7.geometry}
                material={materials["Material.002"]}
              />
              <mesh
                geometry={nodes.Object_8.geometry}
                material={materials["Material.003"]}
              />
            </group>
            <mesh
              geometry={nodes.Object_5.geometry}
              material={materials["Material.005"]}
              position={[-142.94, -32.75, -5922.87]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={100}
            />
            <mesh
              geometry={nodes.Object_10.geometry}
              material={materials["Material.002"]}
              position={[-182.68, 35.49, 1926.62]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/css_logo_3d_model-transformed.glb");
