/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 instagram.gltf --transform
Author: darthrahuna (https://sketchfab.com/darthrahuna)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/instagram-cd3cf2c2fd7844779bb3290e86110fb0
Title: instagram
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/instagram-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <lineSegments
          geometry={nodes.Object_2.geometry}
          material={materials.alpha}
        />
        <mesh geometry={nodes.Object_3.geometry} material={materials.alpha} />
      </group>
    </group>
  );
}

useGLTF.preload("/instagram-transformed.glb");
