/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 piano.gltf --transform
Author: Okapiguy (https://sketchfab.com/Okapiguy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/grand-piano-and-stool-5cf67f2b64d6428dad94524d6d12aeea
Title: Grand Piano and Stool
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/piano-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.polySurface469_lambert5_0.geometry}
          material={materials.lambert5}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/piano-transformed.glb");
