/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 planet.gltf --transform
Author: Mario.Meza (https://sketchfab.com/uriel19961810)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/planet-earth-4a654cc4c2f9464791073e245f43c2e7
Title: planet Earth
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/planet-transformed.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null} scale={0.01}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="6c9739b702654f608e512cbfad62b594fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Earth_Diffuse_6K"
                  position={[-0.62, 0, 3.48]}
                  rotation={[Math.PI / 2, 0, 2.41]}
                  scale={[-42794.53, -42794.54, -42794.54]}
                >
                  <mesh
                    name="Earth_Diffuse_6K_Earth_Diffuse_6Kmain_0"
                    geometry={
                      nodes.Earth_Diffuse_6K_Earth_Diffuse_6Kmain_0.geometry
                    }
                    material={materials["Earth_Diffuse_6K.main"]}
                  />
                </group>
                <group
                  name="Earth_Diffuse_6K001"
                  position={[-0.62, 0, 3.48]}
                  rotation={[Math.PI / 2, 0, 2.9]}
                  scale={-42976.48}
                >
                  <mesh
                    name="Earth_Diffuse_6K001_Earth_Diffuse_6K001_0"
                    geometry={
                      nodes.Earth_Diffuse_6K001_Earth_Diffuse_6K001_0.geometry
                    }
                    material={materials["Earth_Diffuse_6K.001"]}
                  />
                  <mesh
                    name="Earth_Diffuse_6K001_Earth_Diffuse_6K001_0_1"
                    geometry={
                      nodes.Earth_Diffuse_6K001_Earth_Diffuse_6K001_0_1.geometry
                    }
                    material={materials["Earth_Diffuse_6K.001"]}
                  />
                  <mesh
                    name="Earth_Diffuse_6K001_Earth_Diffuse_6K001_0_2"
                    geometry={
                      nodes.Earth_Diffuse_6K001_Earth_Diffuse_6K001_0_2.geometry
                    }
                    material={materials["Earth_Diffuse_6K.001"]}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/planet-transformed.glb");
