/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 smile.gltf --transform
Author: i.deal3d (https://sketchfab.com/i.deal3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/smile-icon-message-72d989305cd947a9977963cff30ab4ed
Title: Smile Icon Message
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/smile-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.72, 0.15]}>
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials["Material.009"]}
        />
        <mesh geometry={nodes.Object_5.geometry} material={materials.lips} />
      </group>
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials["brows.001"]}
        position={[-0.04, 0.74, 0.26]}
        rotation={[1.31, -0.02, 0.39]}
      />
      <mesh
        geometry={nodes.Object_9.geometry}
        material={materials["brows.001"]}
        position={[0.05, 0.75, 0.25]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_11.geometry}
        material={materials["brows.001"]}
        position={[0, 0.68, 0.25]}
        rotation={[0.11, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_13.geometry}
        material={materials["Material.014"]}
        position={[-0.02, 0.63, 0.24]}
        rotation={[1.59, -0.24, 0.09]}
      />
      <mesh
        geometry={nodes.Object_15.geometry}
        material={materials["Material.015"]}
        position={[0.04, 0.75, 0.27]}
        rotation={[-0.33, 0.23, 0.11]}
      />
      <mesh
        geometry={nodes.Object_17.geometry}
        material={materials["Material.015"]}
        position={[-0.04, 0.74, 0.27]}
        rotation={[-0.13, -0.31, -0.08]}
      />
      <mesh
        geometry={nodes.Object_19.geometry}
        material={materials.Material}
        position={[0, 0.72, 0.11]}
      />
    </group>
  );
}

useGLTF.preload("/smile-transformed.glb");
